### ISSUE TITLE
Wikimedia\Rdbms\DBTransactionStateError from line 1312 of "Database.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticInterlanguageLinks#70]
### Setup and configuration

- MediaWiki | 1.31.1 (c520c19)05:30, 26 March 2019
- PHP | 7.2.15-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.38-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.0.1 (37c9525) 01:30, 25 January 2019
- Semantic Interlanguage Links | 1.5.0 (4f1d018)  23:43, 8 Oct 2018

### Issue
```
[406141856ba5fb1f27861b46] /w/index.php?title=Semantic_MediaWiki&action=submit Wikimedia\Rdbms\DBTransactionStateError from line 1312 of /../w/includes/libs/rdbms/database/Database.php: Cannot execute query from SMW\SQLStore\EntityStore\SemanticDataLookup::fetchSemanticData while transaction status is ERROR.
```

### Stack trace

```
#0 /../w/includes/libs/rdbms/database/Database.php(1095): Wikimedia\Rdbms\Database->assertTransactionStatus(string, string)
#1 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(442): Wikimedia\Rdbms\Database->query(string, string, boolean)
#2 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/SemanticDataLookup.php(301): SMW\MediaWiki\Connection\Database->query(string, string)
#3 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingSemanticDataLookup.php(258): SMW\SQLStore\EntityStore\SemanticDataLookup->fetchSemanticData(integer, SMW\DIWikiPage, SMW\SQLStore\PropertyTableDefinition)
#4 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingSemanticDataLookup.php(227): SMW\SQLStore\EntityStore\CachingSemanticDataLookup->fetchFromCache(integer, SMW\DIWikiPage, SMW\SQLStore\PropertyTableDefinition)
#5 /../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(218): SMW\SQLStore\EntityStore\CachingSemanticDataLookup->getSemanticDataFromTable(integer, SMW\DIWikiPage, SMW\SQLStore\PropertyTableDefinition, NULL)
#6 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/NativeEntityLookup.php(64): SMWSQLStore3Readers->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#7 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingEntityLookup.php(243): SMW\SQLStore\EntityStore\NativeEntityLookup->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#8 /../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(194): SMW\SQLStore\EntityStore\CachingEntityLookup->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#9 /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php(302): SMWSQLStore3->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#10 /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php(286): SMW\Query\Result\ResultFieldMatchFinder->doFetchPropertyValues(array, SMW\DataValues\PropertyValue)
#11 /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php(194): SMW\Query\Result\ResultFieldMatchFinder->getResultContent(SMW\DIWikiPage)
#12 /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php(144): SMW\Query\Result\ResultFieldMatchFinder->getResultsForProperty(SMW\DIWikiPage)
#13 /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php(262): SMW\Query\Result\ResultFieldMatchFinder->findAndMatch(SMW\DIWikiPage)
#14 /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php(145): SMWResultArray->loadContent()
#15 /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php(179): SMWResultArray->getNextDataItem()
#16 /../w/extensions/SemanticInterlanguageLinks/src/InterlanguageLinksLookup.php(285): SMWResultArray->getNextDataValue()
#17 /../w/extensions/SemanticInterlanguageLinks/src/InterlanguageLinksLookup.php(140): SIL\InterlanguageLinksLookup->iterateQueryResultToFindLanguageTargetLinks(SMWQueryResult, array)
#18 /../w/extensions/SemanticInterlanguageLinks/src/InterlanguageListParserFunction.php(76): SIL\InterlanguageLinksLookup->queryLanguageTargetLinks(SIL\InterlanguageLink)
#19 /../w/extensions/SemanticInterlanguageLinks/src/InterlanguageListParserFunction.php(63): SIL\InterlanguageListParserFunction->getLanguageTargetLinks(SIL\InterlanguageLink)
#20 /../w/extensions/SemanticInterlanguageLinks/src/ParserFunctionFactory.php(86): SIL\InterlanguageListParserFunction->parse(string, string)
#21 /../w/includes/parser/Parser.php(3426): SIL\ParserFunctionFactory->SIL\{closure}(Parser, string, string)
#22 /../w/includes/parser/Parser.php(3127): Parser->callParserFunction(PPFrame_DOM, string, array)
#23 /../w/includes/parser/Preprocessor_DOM.php(1277): Parser->braceSubstitution(array, PPFrame_DOM)
#24 /../w/includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#25 /../w/includes/parser/Parser.php(1293): Parser->replaceVariables(string)
#26 /../w/includes/parser/Parser.php(443): Parser->internalParse(string)
#27 /../w/includes/content/WikitextContent.php(323): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#28 /../w/includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#29 /../w/includes/page/WikiPage.php(2129): AbstractContent->getParserOutput(Title, NULL, ParserOptions)
#30 /../w/extensions/SpamBlacklist/includes/SpamBlacklistHooks.php(31): WikiPage->prepareContentForEdit(WikitextContent)
#31 /../w/includes/Hooks.php(177): SpamBlacklistHooks::filterMergedContent(RequestContext, WikitextContent, Status, string, User, boolean)
#32 /../w/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#33 /../w/includes/EditPage.php(1679): Hooks::run(string, array)
#34 /../w/includes/EditPage.php(2120): EditPage->runPostMergeFilters(WikitextContent, Status, User)
#35 /../w/includes/EditPage.php(1506): EditPage->internalAttemptSave(NULL, boolean)
#36 /../w/includes/EditPage.php(652): EditPage->attemptSave(NULL)
#37 /../w/includes/actions/EditAction.php(60): EditPage->edit()
#38 /../w/includes/actions/SubmitAction.php(38): EditAction->show()
#39 /../w/includes/MediaWiki.php(500): SubmitAction->show()
#40 /../w/includes/MediaWiki.php(294): MediaWiki->performAction(Article, Title)
#41 /../w/includes/MediaWiki.php(861): MediaWiki->performRequest()
#42 /../w/includes/MediaWiki.php(524): MediaWiki->main()
#43 /../w/index.php(42): MediaWiki->run()
#44 {main}
```

### Steps to reproduce
Main Page of www.s-wm.o on the new server. Needless to say that it is only this page.

**Comment by mwjames** [comment]
> [406141856ba5fb1f27861b46]
> /w/index.php?title=Semantic_MediaWiki&action=submit
> Wikimedia\Rdbms\DBTransactionStateError from line 1312 of
> /../w/includes/libs/rdbms/database/Database.php: Cannot execute query from
> SMW\SQLStore\EntityStore\SemanticDataLookup::fetchSemanticData while
> transaction status is ERROR.

Not seen this one before and to be honest, I have no idea what "Cannot
execute query from ... transaction status is ERROR" [0] means as an
error or what part of the query can caused it because
`SemanticDataLookup::fetchSemanticData` only involves `SELECT` queries
(no writes) therefore there shouldn't be any transactions.

Also, given that nothing has changed from a software side except for
MySQL -> MariaDB maybe some settings on the new server is causing some
transaction or binlog.

Cheers

[0] https://phabricator.wikimedia.org/search/query/CXK.GA6VD54I/#R

**Comment by kghbln** [comment]
Interestingly I saw this on Main Page only and not on other pages using SIL. However after uninstalling SIL the error goes away. Looks like I have to dig into MariaDB.

**Comment by mwjames** [comment]
> Interestingly I saw this on Main Page only and not on other pages using SIL.
> However after uninstalling SIL the error goes away. Looks like I have to dig
> into MariaDB.

[0] shows what this method is suppose to be doing, not writes, no temp
tables so there shouldn't be any transaction.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/3.0.x/src/SQLStore/EntityStore/SemanticDataLookup.php#L195-L209

**Comment by mwjames** [comment]
> #29 /../w/includes/page/WikiPage.php(2129): AbstractContent->getParserOutput(Title, NULL, ParserOptions)
#30 /../w/extensions/SpamBlacklist/includes/SpamBlacklistHooks.php(31):
WikiPage->prepareContentForEdit(WikitextContent)
#31 /../w/includes/Hooks.php(177):
SpamBlacklistHooks::filterMergedContent(RequestContext,
WikitextContent, Status, string, User, boolean)

I saw `SpamBlacklist` being active here, so can you check whether this
is causing an issue with SIL (by deactivating `SpamBlacklist`) or not.

**Comment by kghbln** [comment]
>  I saw `SpamBlacklist` being active here, so can you check whether this is causing an issue with SIL (by deactivating `SpamBlacklist`) or not.

Will do, however tomorrow. The whole setup is somewhat handicapped. Moreover I really tired now. I am willing to cheerfully kick SpamBlacklist for the good cause. Keeping fingers crossed.

**Comment by kghbln** [comment]
>  I saw `SpamBlacklist` being active here, so can you check whether this is causing an issue with SIL (by deactivating `SpamBlacklist`) or not.

No, unfortunately this does not change anything.

**Comment by kghbln** [comment]
I believe this is causing the error:

```
Error: 1267 Illegal mix of collations (latin1_bin,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
```
So I have to fix the database

**Comment by kghbln** [comment]
> I believe this is causing the error:

Affirmative. And yes it was a rodeo to fix this and I am not sure if there was a data loss or not, because e.g. 

https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki/pt

says

The combination "pt":"Semantic MediaWiki" already exists for page "Página principal pt" therefore no additional interlanguage annotation was created.

Page "Página principal pt" however does not exist and "Página principal (pt)" neither. I am pretty sure that there was once a redirect from "Página principal (pt)" to "Semantic MediaWiki/pt".

I am now doing a full data rebuild and let's see where we go from there.

**Comment by kghbln** [comment]
On the other hand many of the broken redirect which I ignored during the past three years are now resolved: https://www.semantic-mediawiki.org/wiki/Special:BrokenRedirects

I lean towards, "Sorry folks, that's it, it will not get better". The database was a disaster waiting to unfold during its time on the old server.

**Comment by kghbln** [comment]
Omg, the database is totally corrupted. I will have to switch MariaDB from utf8 to latin. Not sure if we will loose the sandbox doing so.

**Comment by krabina** [comment]
How did you fix the problem I am getting similar errors when doing a complete rebuildData:

```
[46b8717b459caf5b2c94ac91] [no req]   Wikimedia\Rdbms\DBTransactionStateError from line 1312 of includes/libs/rdbms/database/Database.php: Cannot execute query from SMW\SQLStore\Rebuilder\Rebuilder::getMaxId while transaction status is ERROR.
Backtrace:
#0 includes/libs/rdbms/database/Database.php(1095): Wikimedia\Rdbms\Database->assertTransactionStatus(string, string)
#1 includes/libs/rdbms/database/Database.php(1653): Wikimedia\Rdbms\Database->query(string, string)
#2 includes/libs/rdbms/database/Database.php(1479): Wikimedia\Rdbms\Database->select(string, string, string, string, array, array)
#3 [internal function]: Wikimedia\Rdbms\Database->selectField(string, string, string, string, array)
#4 includes/libs/rdbms/database/DBConnRef.php(49): call_user_func_array(array, array)
#5 includes/libs/rdbms/database/DBConnRef.php(241): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#6 /extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(625): Wikimedia\Rdbms\DBConnRef->selectField(string, string, string, string, array)
#7 extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(166): SMW\MediaWiki\Connection\Database->selectField(string, string, string, string)
#8 extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(353): SMW\SQLStore\Rebuilder\Rebuilder->getMaxId()
#9 extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(200): SMW\Maintenance\DataRebuilder->rebuild_all()
#10 extensions/SemanticMediaWiki/maintenance/rebuildData.php(202): SMW\Maintenance\DataRebuilder->rebuild()
#11 maintenance/doMaintenance.php(94): SMW\Maintenance\rebuildData->execute()
#12 extensions/SemanticMediaWiki/maintenance/rebuildData.php(261): require_once(string)
#13 {main}
```

**Comment by krabina** [comment]
ah. I see. fixed this by re-running update.php.
